In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Darren\Desktop\PythonPratic\City+Weather.csv")
df

          Date         City  Temperature  WindSpeed(hpa)           Description
0   2019-07-30      Wembley         15.0         1017.28            Light rain
1   2019-07-31      Wembley         17.9         1014.75         Moderate rain
2   2019-08-01      Wembley         17.8         1014.77  Heavy intensity rain
3   2019-08-02      Wembley         24.4         1014.26                  Rain
4   2019-07-30        Tokyo         29.6         1000.47         Moderate rain
5   2019-07-31        Tokyo         25.1         1004.45            Light rain
6   2019-08-01        Tokyo         22.3          999.28  Heavy intensity rain
7   2019-08-02        Tokyo         23.3         1003.97            Light rain
8   2019-07-30  Los Angeles         17.7         1015.04          Sky is clear
9   2019-07-31  Los Angeles         22.6         1015.40          Sky is clear
10  2019-08-01  Los Angeles         25.4         1014.54          Sky is clear
11  2019-08-02  Los Angeles         24.4         1014.65            Few clouds

In [10]:
#id_vars 想要在新的DF當中不變得Columns 例如 在新的數據表裡面有日期的Date
df1 = pd.melt(df,id_vars = ["Date","City"])

df1
#pd.melt?

          Date         City        variable                 value
0   2019-07-30      Wembley     Temperature                  15.0
1   2019-07-31      Wembley     Temperature                  17.9
2   2019-08-01      Wembley     Temperature                  17.8
3   2019-08-02      Wembley     Temperature                  24.4
4   2019-07-30        Tokyo     Temperature                  29.6
5   2019-07-31        Tokyo     Temperature                  25.1
6   2019-08-01        Tokyo     Temperature                  22.3
7   2019-08-02        Tokyo     Temperature                  23.3
8   2019-07-30  Los Angeles     Temperature                  17.7
9   2019-07-31  Los Angeles     Temperature                  22.6
10  2019-08-01  Los Angeles     Temperature                  25.4
11  2019-08-02  Los Angeles     Temperature                  24.4
12  2019-07-30      Wembley  WindSpeed(hpa)               1017.28
13  2019-07-31      Wembley  WindSpeed(hpa)               1014.75
14  2019-08-01      Wembley  WindSpeed(hpa)               1014.77
15  2019-08-02      Wembley  WindSpeed(hpa)               1014.26
16  2019-07-30        Tokyo  WindSpeed(hpa)               1000.47
17  2019-07-31        Tokyo  WindSpeed(hpa)               1004.45
18  2019-08-01        Tokyo  WindSpeed(hpa)                999.28
19  2019-08-02        Tokyo  WindSpeed(hpa)               1003.97
20  2019-07-30  Los Angeles  WindSpeed(hpa)               1015.04
21  2019-07-31  Los Angeles  WindSpeed(hpa)                1015.4
22  2019-08-01  Los Angeles  WindSpeed(hpa)               1014.54
23  2019-08-02  Los Angeles  WindSpeed(hpa)               1014.65
24  2019-07-30      Wembley     Description            Light rain
25  2019-07-31      Wembley     Description         Moderate rain
26  2019-08-01      Wembley     Description  Heavy intensity rain
27  2019-08-02      Wembley     Description                  Rain
28  2019-07-30        Tokyo     Description         Moderate rain
29  2019-07-31        Tokyo     Description            Light rain
30  2019-08-01        Tokyo     Description  Heavy intensity rain
31  2019-08-02        Tokyo     Description            Light rain
32  2019-07-30  Los Angeles     Description          Sky is clear
33  2019-07-31  Los Angeles     Description          Sky is clear
34  2019-08-01  Los Angeles     Description          Sky is clear
35  2019-08-02  Los Angeles     Description            Few clouds

In [11]:
#如果只是要顯示某個部份的話可以新增條件，只顯示溫度的部分
df1 = pd.melt(df,id_vars = ["Date"])
df1[df1["variable"] == "Temperature"]

          Date     variable value
12  2019-07-30  Temperature  15.0
13  2019-07-31  Temperature  17.9
14  2019-08-01  Temperature  17.8
15  2019-08-02  Temperature  24.4
16  2019-07-30  Temperature  29.6
17  2019-07-31  Temperature  25.1
18  2019-08-01  Temperature  22.3
19  2019-08-02  Temperature  23.3
20  2019-07-30  Temperature  17.7
21  2019-07-31  Temperature  22.6
22  2019-08-01  Temperature  25.4
23  2019-08-02  Temperature  24.4

In [6]:
#不只是Date不改變還想要增加城市也不改變的話,會有順序問題
df1 = pd.melt(df,id_vars = ["Date","City"],value_vars = ["Temperature"])
df1

          Date         City     variable  value
0   2019-07-30      Wembley  Temperature   15.0
1   2019-07-31      Wembley  Temperature   17.9
2   2019-08-01      Wembley  Temperature   17.8
3   2019-08-02      Wembley  Temperature   24.4
4   2019-07-30        Tokyo  Temperature   29.6
5   2019-07-31        Tokyo  Temperature   25.1
6   2019-08-01        Tokyo  Temperature   22.3
7   2019-08-02        Tokyo  Temperature   23.3
8   2019-07-30  Los Angeles  Temperature   17.7
9   2019-07-31  Los Angeles  Temperature   22.6
10  2019-08-01  Los Angeles  Temperature   25.4
11  2019-08-02  Los Angeles  Temperature   24.4

In [13]:
#如果我們部輸入value_vars的話 並且改動Column欄位名稱
df1 = pd.melt(df,id_vars = ["Date","City"],var_name = "Property",value_name = "value Name")
#pd.melt?
df1

          Date         City        Property            value Name
0   2019-07-30      Wembley     Temperature                  15.0
1   2019-07-31      Wembley     Temperature                  17.9
2   2019-08-01      Wembley     Temperature                  17.8
3   2019-08-02      Wembley     Temperature                  24.4
4   2019-07-30        Tokyo     Temperature                  29.6
5   2019-07-31        Tokyo     Temperature                  25.1
6   2019-08-01        Tokyo     Temperature                  22.3
7   2019-08-02        Tokyo     Temperature                  23.3
8   2019-07-30  Los Angeles     Temperature                  17.7
9   2019-07-31  Los Angeles     Temperature                  22.6
10  2019-08-01  Los Angeles     Temperature                  25.4
11  2019-08-02  Los Angeles     Temperature                  24.4
12  2019-07-30      Wembley  WindSpeed(hpa)               1017.28
13  2019-07-31      Wembley  WindSpeed(hpa)               1014.75
14  2019-08-01      Wembley  WindSpeed(hpa)               1014.77
15  2019-08-02      Wembley  WindSpeed(hpa)               1014.26
16  2019-07-30        Tokyo  WindSpeed(hpa)               1000.47
17  2019-07-31        Tokyo  WindSpeed(hpa)               1004.45
18  2019-08-01        Tokyo  WindSpeed(hpa)                999.28
19  2019-08-02        Tokyo  WindSpeed(hpa)               1003.97
20  2019-07-30  Los Angeles  WindSpeed(hpa)               1015.04
21  2019-07-31  Los Angeles  WindSpeed(hpa)                1015.4
22  2019-08-01  Los Angeles  WindSpeed(hpa)               1014.54
23  2019-08-02  Los Angeles  WindSpeed(hpa)               1014.65
24  2019-07-30      Wembley     Description            Light rain
25  2019-07-31      Wembley     Description         Moderate rain
26  2019-08-01      Wembley     Description  Heavy intensity rain
27  2019-08-02      Wembley     Description                  Rain
28  2019-07-30        Tokyo     Description         Moderate rain
29  2019-07-31        Tokyo     Description            Light rain
30  2019-08-01        Tokyo     Description  Heavy intensity rain
31  2019-08-02        Tokyo     Description            Light rain
32  2019-07-30  Los Angeles     Description          Sky is clear
33  2019-07-31  Los Angeles     Description          Sky is clear
34  2019-08-01  Los Angeles     Description          Sky is clear
35  2019-08-02  Los Angeles     Description            Few clouds