In [15]:
import pandas as pd
def convert_stock(cell):
    if cell == "0":
        return "the stock is low count"
    return cell

def convert_describe(cell):
    if cell == "沒有資料":
        return "no data can set"
    return cell

df = pd.read_excel(r'C:\Users\e6380\Desktop\PythonPratic\shoes.xlsx',converters = {
    "產品數量":convert_stock,
    "產品描述":convert_describe
})


    
#如果Excel裡面有很多Sheet的時候需要
#df = pd.read_excel(r'C:\Users\e6380\Desktop\PythonPratic\shoes.xlsx',"Sheet 1 - sheet名稱")
df

,產品名稱,產品描述,價格,尺寸,庫存,產品數量
0,380671,no data can set,NaN,37,1.0,1
1,380671,no data can set,NaN,38,1.0,1
2,Brilliant,no data can set,6800.0,36,1.0,1
3,Brilliant,no data can set,6800.0,37,1.0,1
4,Brilliant,no data can set,6800.0,37,1.0,1
...,...,...,...,...,...,...
992,Little Elsa,光潔如絲的高級鍛料包覆鞋身，佐以五朵精緻花蕊。蕊心點綴著艾莎公主施以魔法晶瑩剔透的耀眼冰晶，...,2680.0,4,1.0,1
993,Little Elsa,光潔如絲的高級鍛料包覆鞋身，佐以五朵精緻花蕊。蕊心點綴著艾莎公主施以魔法晶瑩剔透的耀眼冰晶，...,2680.0,5,1.0,1
994,Little Elsa,光潔如絲的高級鍛料包覆鞋身，佐以五朵精緻花蕊。蕊心點綴著艾莎公主施以魔法晶瑩剔透的耀眼冰晶，...,2680.0,6,1.0,1
995,Little Elsa,光潔如絲的高級鍛料包覆鞋身，佐以五朵精緻花蕊。蕊心點綴著艾莎公主施以魔法晶瑩剔透的耀眼冰晶，...,2680.0,7,1.0,1
996,Little Elsa,光潔如絲的高級鍛料包覆鞋身，佐以五朵精緻花蕊。蕊心點綴著艾莎公主施以魔法晶瑩剔透的耀眼冰晶，...,2680.0,9,1.0,1

In [16]:
df.to_excel("newShoes.xlsx",sheet_name = "newShoes")